### ISSUE TITLE
Overriding Global Git Config

### ISSUE THREAD

**Issue by jamesward** [apple/pkl-package-docs#4]
Running `./gradlew generateDocs` overwrites global git config:
https://github.com/apple/pkl-package-docs/blob/main/src/main/kotlin/org/pkl/package_docs/PackageDocs.kt#L97-L98

Which is not great for developers who try to run this on their machines.

**Comment by bioball** [comment]
Sorry about that. This command is meant for CI only, but yeah even then there's no reason to override global git config.
