### ISSUE TITLE
PKL package documentation includes erroneous module URI's for imports

### ISSUE THREAD

**Issue by Senjai** [apple/pkl-package-docs#6]
Note I'm recording this in case I don't get to fixing it myself, I wouldn't mind taking a stab at it.

Example: https://pkl-lang.org/package-docs/pkg.pkl-lang.org/pkl-pantry/pkl.experimental.deepToTyped/current/index.html

The module URI linked here should be `package://pkg.pkl-lang.org/pkl-pantry/pkl.experimental.deepToTyped@1.0.0#/deepToTyped.pkl`

So far that I can tell, this is consistently incorrect

(another example: https://pkl-lang.org/package-docs/pkg.pkl-lang.org/pkl-pantry/io.prometheus/current/Rule/index.html)

**Comment by holzensp** [comment]
Go for it! This sure needs fixing :)

**Comment by bioball** [comment]
Fixed in 0.25.3!

**Comment by Senjai** [comment]
Apologies for the delay there @bioball I got absolutely slammed at work 😓 thank you!
